server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.37.194.170:3306/zwnl-user?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: zwnl
#  application:
#    name: wlmtsys-user
#  cloud:
#    nacos:
#      config:
#        import-check:
#          enabled: false # 禁用导入检查
#        server-addr: 192.168.200.130:8848 # Nacos 服务器地址
#        file-extension: yml # 配置文件扩展名
#      discovery:
#        server-addr: 192.168.200.130:8848 # 服务发现服务器地址

